Init for PE
* Almost changed everything.
* Create ccache for pe as of now
* Reduce RAM to 25GB as of now
* don't download ccache as of now. etc

diff --git a/build b/build
--- a/build
+++ b/build
@@ -1,13 +1,12 @@
 #!/bin/bash
 cd /tmp/rom # Depends on where source got synced
 
-curl https://del.dog/raw/ypyttaxone >> gms_full.mk
-mv gms_full.mk vendor/gms/
 rm -rf device/generic/opengl-transport
 
 # Normal build steps
 . build/envsetup.sh
-lunch derp_vince-userdebug
+lunch aosp_vince-userdebug
+export SELINUX_IGNORE_NEVERALLOWS=true
 export CCACHE_DIR=/tmp/ccache
 export CCACHE_EXEC=$(which ccache)
 export USE_CCACHE=1
@@ -18,12 +17,12 @@ ccache -z # Clear old stats, so monitor script will provide real ccache statisti
 # Next 8 lines should be run first to collect ccache and then upload, after doning it 1 or 2 times, our ccache will help to build without these 8 lines.
 #mka sepolicy
 #mka api-stubs-docs || echo no problem, we need ccache
-#mka system-api-stubs-docs || echo no problem we need ccache
-#mka test-api-stubs-docs || echo no problem, we need ccache
-#mka derp -j10 & # dont remove that '&'
-#sleep 75m
-#kill %1
-#ccache -s
+mka system-api-stubs-docs || echo no problem we need ccache
+mka test-api-stubs-docs || echo no problem, we need ccache
+mka bacon -j10 & # dont remove that '&'
+sleep 85m
+kill %1
+ccache -s
 #and dont use below codes for first 1 or 2 times, to get ccache uploaded,
 
 
@@ -35,12 +34,12 @@ ccache -z # Clear old stats, so monitor script will provide real ccache statisti
 
 # It's recommended to use google drive(rclone) as upload solution for coping with the time limit. Un-comment next 3 lines to upload with rclone in drive. Also change drive and junk according to your config name, uploading folder of drive
 up(){
-	time rclone copy $1 drive:junk -P # drive is my rclone config name, 
+	time rclone copy $1 drive:junk -P # drive is my rclone config name,
 }
 
 tg(){
-	bot_api=$bot_api_code # Your tg bot api 
-	your_telegram_id=$1 # No need to touch 
+	bot_api=$bot_api_code # Your tg bot api
+	your_telegram_id=$1 # No need to touch
 	msg=$2 # No need to touch
 	curl -s "https://api.telegram.org/bot${bot_api}/sendmessage" --data "text=$msg&chat_id=${your_telegram_id}"
 }
@@ -48,22 +47,22 @@ tg(){
 id=-1001273969756 # Your telegram id
 
 #get some ccache message
-#tg $id "Got some ccache"
+tg $id "Got some ccache (PE)"
 
 # Create rclone config first
-mkdir -p ~/.config/rclone
-echo "$rclone_config" > ~/.config/rclone/rclone.conf 
+#mkdir -p ~/.config/rclone
+#echo "$rclone_config" > ~/.config/rclone/rclone.conf
 
 # Upload rom zip file if succeed to build! Send notification to tg! And send shell to tg if build fails!
 
 # Let's compile by parts! Coz of ram issue!
-mka api-stubs-docs || echo no problem
-mka system-api-stubs-docs || echo no problem
-mka test-api-stubs-docs || echo no problem
+#mka api-stubs-docs || echo no problem
+#mka system-api-stubs-docs || echo no problem
+#mka test-api-stubs-docs || echo no problem
 
-mka derp -j10 \
-        && send_zip=$(up out/target/product/vince/*zip) && tg $id "Build Succeed!
-$send_zip" \
-	    || tmate -S /tmp/tmate.sock new-session -d && tmate -S /tmp/tmate.sock wait tmate-ready && send_shell=$(tmate -S /tmp/tmate.sock display -p '#{tmate_ssh}') && tg $id "Build Failed" && tg $id "$send_shell" && ccache -s && sleep 2h
-up out/target/product/vince/*md5sum
-ccache -s # Let's print ccache statistics finally
+#mka bacon -j10 \
+#        && send_zip=$(up out/target/product/vince/*zip) && tg $id "Build Succeed!
+#$send_zip" \
+#	    || tmate -S /tmp/tmate.sock new-session -d && tmate -S /tmp/tmate.sock wait tmate-ready && send_shell=$(tmate -S /tmp/tmate.sock display -p '#{tmate_ssh}') && tg $id "Build Failed" && tg $id "$send_shell" && ccache -s && sleep 2h
+#up out/target/product/vince/*md5sum
+#ccache -s # Let's print ccache statistics finally
